# Generated by Django 5.1 on 2024-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoprint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoprint',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='photoprint',
            options={'verbose_name_plural': 'Распечатка фотографий'},
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
