# Generated by Django 5.1 on 2024-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0004_alter_service_options_alter_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sizes',
        ),
        migrations.AddField(
            model_name='service',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
