# Generated by Django 5.1 on 2024-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0007_remove_service_height_remove_service_width_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='service',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ширина'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
