# Generated by Django 5.1 on 2024-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0008_service_height_service_width_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='service',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
