# Generated by Django 5.1 on 2024-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0010_status_alter_service_options_remove_service_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='services', to='PhotoPrint.si'),
        ),
    ]
