# Generated by Django 5.1 on 2024-08-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0011_service_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si',
            name='name',
        ),
        migrations.AddField(
            model_name='si',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='si',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='si',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='PhotoPrint.service'),
        ),
    ]
