# Generated by Django 5.1 on 2024-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoPrint', '0013_remove_service_sizes_alter_si_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='si',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
